version: '2'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    command: filebeat -e -strict.perms=false
    #volumnes mount depend on you OS ( Windows or Linux )
    volumes:
      - /c/cygwin64/home/nam/projects/docker-elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /c/cygwin64/home/nam/projects/docker-elk/filebeat/sample_log:/usr/share/filebeat/logs
    networks:
      - elk
    links:
       - elasticsearch
networks:
  elk:
    driver: bridge
